#!/usr/bin/env python3
# Auto-generated by TreeShellLibraryFactory

import os
from pathlib import Path
from heaven_tree_repl.shells import TreeShell
from heaven_tree_repl.system_config_loader_v2 import SystemConfigLoader


class SkillManagerConfigLoader(SystemConfigLoader):
    """Custom config loader that uses this library's system configs as base."""

    def _get_library_configs_dir(self) -> str:
        """Override to use this library's configs instead of heaven-tree-repl's."""
        library_root = Path(__file__).parent.parent
        return str(library_root / "configs")


class SkillManagerTreeShell(TreeShell):
    """Skill Manager TreeShell - three-tier skill architecture interface."""
    def __init__(self, user_config_path: str = None):
        config_loader = SkillManagerConfigLoader(config_types=["base", "base_zone_config", "base_shortcuts"])
        final_config = config_loader.load_and_validate_configs(user_config_path)

        # Load families and add to config
        families = config_loader.load_families(user_config_path)
        final_config['_loaded_families'] = families

        super().__init__(final_config)
